### ISSUE TITLE
Wrong result

### ISSUE THREAD

**Issue by apurvNfer** [maxlath/load-balance-lines#1]
```sh
cat wikidata_subclasses.json | 
nice -n+19 load-balance-lines jq -c '{id: .id, labels: .labels, subclasses: [.claims.P279[].mainsnak.datavalue.value.id > required_wikidata_subclasses.json
```

Trying to run this command. The file wikidata_subclasses.json is a NDJSON. The output generated has wrong data. For eg. I'm getting **id** from one line and labels from another. What could be the reason for this?

**Comment by maxlath** [comment]
the command in your message seems incomplete
